# Generated by Django 4.1.5 on 2023-04-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaModel',
            fields=[
                ('qna_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=500)),
                ('question_description', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='QnA_Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QnaCommentModel',
            fields=[
                ('qna_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='Qna_comment_image')),
                ('qna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QnA_Forum.qnamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
