# Generated by Django 4.1.5 on 2023-04-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_collegeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegeID',
            field=models.ImageField(default='media/college_id/defult_college_id.jpg', null=True, upload_to='media/college_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/profile_picture/profile_avatar_m.png', upload_to='media/profile_picture'),
        ),
    ]
