# Generated by Django 4.1.5 on 2023-04-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_user_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=600),
        ),
    ]
