# Generated by Django 4.1.5 on 2023-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegeID',
            field=models.ImageField(default='D:\\Works\\DjangoProjects\\note_sharing_venv\\note_sharing_application\\media/college_id/defult_college_id.jpg', null=True, upload_to='college_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='D:\\Works\\DjangoProjects\\note_sharing_venv\\note_sharing_application\\media/profile_picture/profile_avatar_m.png', upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
