# Generated by Django 4.1.5 on 2023-04-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_content', models.TextField(max_length=5000, null=True)),
                ('post_image', models.ImageField(null=True, upload_to='')),
                ('post_file', models.FileField(null=True, upload_to='')),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_liked', models.PositiveIntegerField(default=0)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
